Log retries
Currently we silently retry which makes it unreasonably hard to find
the failures.

Signed-off-by: moritz.kiefer@digitalasset.com <moritz.kiefer@purelyfunctional.org>

diff --git a/.github/actions/nix/run_bash_command_in_nix/action.yml b/.github/actions/nix/run_bash_command_in_nix/action.yml
--- a/.github/actions/nix/run_bash_command_in_nix/action.yml
+++ b/.github/actions/nix/run_bash_command_in_nix/action.yml
@@ -182,9 +182,13 @@ runs:
               }
               cmd_wrapper && break
 
+              exit_code="$?"
+
               # TODO(#615): support a conditional retry (cmd_retry_condition argument in CCI), used for retrying if VPN failed
 
               n=$[$n+1]
+
+              echo "Attempt $n failed with exit code $exit_code, retrying"
           done
 
           if [ $n -gt $MAX_RETRY ]; then
